version: '3.6'

services:
  nginx:
    build:
      context: '../nginx'
      dockerfile: Dockerfile.dev
    restart: always
    volumes: 
      - ../nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "3050:80"
    depends_on: 
      - api
      - client
    networks:
      - course

  api:
    depends_on:
      - redis
      - postgres
    build: 
      context: ../server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ../server:/app
    env_file: 
      - ./env/local.env
    # command: sh ./wait-for-it.sh npm run dev
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run dev'
    networks:
      - course
  client:
    build:
      context: ../fe
      dockerfile: Dockerfile.dev
   
    stdin_open: true
    volumes:
      - /app/node_modules
      - ../fe:/app
    networks:
      - course
  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ../worker:/app
    env_file: 
      - ./env/local.env
    networks:
      - course
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 1
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
networks:
  course:
    # Use a custom driver
    driver: bridge